name: Gridsome Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - run: git config --global user.email "dscgranada@gmail.com"
      - run: git config --global user.name "DSC-UGR"
      - run: npm install
      - run: npm run deploy
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          PRODUCTION: "true"
